---

- name: download and extract binary
  unarchive:
    src: "{{ consul_pkg_url }}"
    dest: "{{ consul_bin_dir }}"
    remote_src: yes
    creates: "{{ consul_bin }}"

- name: create configuration and data directories
  file:
    name: "{{ item }}"
    state: directory
  with_items:
    - "{{ consul_dirs }}"
