---

- hosts: all
  become: yes
  roles:
    - common
    - consul

- hosts: worker
  become: yes
  roles:
    - docker
    - nomad

- hosts: deploy
  become: yes
  roles:
    - cabify

- hosts: proxy
  become: yes
  roles:
    - haproxy
    - consul-template
