---

docker_apt_package: docker-ce

docker_apt_package_dependencies:
  - "linux-image-extra-{{ facter_kernelrelease }}"
  - linux-image-extra-virtual

docker_apt_repository: "deb [arch={{ facter_architecture }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

docker_gpg_keyserver: https://download.docker.com/linux/ubuntu/gpg
docker_gpg_keyserver_fingerprint: 0EBFCD88

docker_insecure_registry_url: registry.service.consul:5000

docker_service: docker
