---

consul_bin: "{{ consul_bin_dir }}/consul"
consul_bin_dir: /usr/bin

consul_bootstrap_servers: 2

consul_dir_config: /etc/consul
consul_dir_data: /var/lib/consul
consul_dir_log: /var/log/consul

consul_dirs:
  - "{{ consul_dir_config }}"
  - "{{ consul_dir_data }}"
  - "{{ consul_dir_log }}"

consul_log_file: "{{ consul_dir_log }}/consul.log"

consul_pkg_url: "https://releases.hashicorp.com/consul/{{ consul_pkg_version }}/consul_{{ consul_pkg_version }}_linux_amd64.zip"
consul_pkg_version: 1.0.6

consul_recursors:
  - 8.8.8.8
  - 8.8.4.4

consul_servers:
  - 192.168.33.10
  - 192.168.33.11
  - 192.168.33.12
  - 192.168.33.100

consul_upstart_file: /etc/init/consul.conf
